language: python
sudo: false
env:
  - consumer_key=f8fee29a-0071-4c10-bb35-aa1887b3ea00 consumer_secret=a25e93e5-9cb1-49b6-aab4-e4c60c16d352 authentic_usagers_hostname=usagers.staging.imio.be authentic_agents_hostname=agents.staging.imio.be OU=myou application_id=iasmartweb
cache:
  directories:
  - eggs
  - downloads
matrix:
  fast_finish: true

matrix:
  include:
    - python: "2.7"
      env: PLONE_VERSION=4.3.x authentic_agents_hostname=agents.staging.imio.be
    - python: "3.6"
      env: PLONE_VERSION=5.2.x authentic_agents_hostname=agents.staging.imio.be
install:
  - pip install -r requirements.txt
  - buildout -c plone$PLONE_VERSION.cfg -N buildout:download-cache=downloads code-analysis:return-status-codes=True annotate
  - buildout -c plone$PLONE_VERSION.cfg -N buildout:download-cache=downloads code-analysis:return-status-codes=True
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage --output-dir=htmlcov
  - pip install -q "coverage<5"
  - pip install -q coveralls
  - coveralls
notifications:
  email:
    - bsuttor@imio.be
