language: python
sudo: false
cache:
  directories:
  - eggs
  - downloads
python:
  - 2.7
matrix:
  fast_finish: true

matrix:
  include:
    - python: "2.7"
      env: PLONE_VERSION=4.3.x
    - python: "2.7"
      env: PLONE_VERSION=5.1.x
install:
  - pip install -r requirements.txt
  - buildout -c plone$PLONE_VERSION.cfg -N buildout:download-cache=downloads code-analysis:return-status-codes=True annotate
  - buildout -c plone$PLONE_VERSION.cfg -N buildout:download-cache=downloads code-analysis:return-status-codes=True
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - firefox -v
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage
  - pip install -q coveralls==0.5
  - coveralls
notifications:
  email:
    - bsuttor@imio.be
